In [1]:
import numpy as np

# Для відтворюваності результатів
np.random.seed(42)

In [2]:
# 1. Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.
vector_20 = np.arange(1, 21)
print('Вектор з перших 20 натуральних чисел:')
print(vector_20)

Вектор з перших 20 натуральних чисел:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
# 2. Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.
matrix_ones = np.ones((4, 4), dtype=int)
print('Матриця 4x4, заповнена одиницями:')
print(matrix_ones)

Матриця 4x4, заповнена одиницями:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [4]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.
matrix_rand_neg1_1 = np.random.uniform(-1, 1, (5, 5))
print('Масив 5x5 з випадковими дійсними числами від -1 до 1:')
print(matrix_rand_neg1_1)

Масив 5x5 з випадковими дійсними числами від -1 до 1:
[[-0.25091976  0.90142861  0.46398788  0.19731697 -0.68796272]
 [-0.68801096 -0.88383278  0.73235229  0.20223002  0.41614516]
 [-0.95883101  0.9398197   0.66488528 -0.57532178 -0.63635007]
 [-0.63319098 -0.39151551  0.04951286 -0.13610996 -0.41754172]
 [ 0.22370579 -0.72101228 -0.4157107  -0.26727631 -0.08786003]]


In [5]:
# 4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
matrix_rand_0_1 = np.random.rand(3, 3)
print('Масив 3x3 з випадковими дійсними числами від 0 до 1:')
print(matrix_rand_0_1)

Масив 3x3 з випадковими дійсними числами від 0 до 1:
[[0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485]
 [0.17052412 0.06505159 0.94888554]]


In [6]:
# 5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.
arr1 = np.random.randint(1, 21, 6)
arr2 = np.random.randint(1, 21, 6)
print('Перший масив:')
print(arr1)
print('Другий масив:')
print(arr2)
print('Поелементне додавання:')
print(arr1 + arr2)
print('Поелементне віднімання:')
print(arr1 - arr2)
print('Поелементне множення:')
print(arr1 * arr2)

Перший масив:
[14 18  9  2 20 15]
Другий масив:
[ 7 12  8 15  3 14]
Поелементне додавання:
[21 30 17 17 23 29]
Поелементне віднімання:
[  7   6   1 -13  17   1]
Поелементне множення:
[ 98 216  72  30  60 210]


In [7]:
# 6. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.
matrix_a = np.random.randint(1, 6, (3, 2))
matrix_b = np.random.randint(1, 6, (2, 4))
matrix_product_ab = np.dot(matrix_a, matrix_b)
print('Матриця 3x2:')
print(matrix_a)
print('Матриця 2x4:')
print(matrix_b)
print('Добуток матриць:')
print(matrix_product_ab)

Матриця 3x2:
[[1 4]
 [2 4]
 [2 2]]
Матриця 2x4:
[[4 5 2 2]
 [4 2 2 4]]
Добуток матриць:
[[20 13 10 18]
 [24 18 12 20]
 [16 14  8 12]]


In [8]:
# 7. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
matrix_transpose_source = np.random.rand(3, 3)
matrix_transposed = matrix_transpose_source.T
print('Початкова матриця 3x3:')
print(matrix_transpose_source)
print('Транспонована матриця:')
print(matrix_transposed)

Початкова матриця 3x3:
[[0.59789998 0.92187424 0.0884925 ]
 [0.19598286 0.04522729 0.32533033]
 [0.38867729 0.27134903 0.82873751]]
Транспонована матриця:
[[0.59789998 0.19598286 0.38867729]
 [0.92187424 0.04522729 0.27134903]
 [0.0884925  0.32533033 0.82873751]]


In [9]:
# 8. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
matrix_c = np.random.randint(1, 11, (3, 3))
matrix_d = np.random.randint(1, 11, (3, 3))
matrix_difference = matrix_c - matrix_d
print('Перша матриця:')
print(matrix_c)
print('Друга матриця:')
print(matrix_d)
print('Різниця матриць:')
print(matrix_difference)

Перша матриця:
[[10  9  9]
 [ 1  9  7]
 [ 9  8  1]]
Друга матриця:
[[8 8 3]
 [1 8 3]
 [3 1 5]]
Різниця матриць:
[[ 2  1  6]
 [ 0  1  4]
 [ 6  7 -4]]


In [10]:
# 9. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.
matrix_e = np.random.randint(-5, 6, (3, 3))
matrix_f = np.random.randint(-5, 6, (3, 3))
matrix_product_ef = np.dot(matrix_e, matrix_f)
print('Перша матриця:')
print(matrix_e)
print('Друга матриця:')
print(matrix_f)
print('Добуток матриць:')
print(matrix_product_ef)

Перша матриця:
[[ 4  1  4]
 [ 3  1  3]
 [ 2 -4 -5]]
Друга матриця:
[[ 1  1  2]
 [-1 -3  2]
 [ 0  5 -3]]
Добуток матриць:
[[  3  21  -2]
 [  2  15  -1]
 [  6 -11  11]]


In [11]:
# 10. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
matrix_sum_rows = np.random.uniform(-1, 1, (3, 3))
column_vector_sums = matrix_sum_rows.sum(axis=1).reshape(-1, 1)
print('Початкова матриця 3x3:')
print(matrix_sum_rows)
print('Вектор-стовпчик сум елементів кожного рядка:')
print(column_vector_sums)

Початкова матриця 3x3:
[[-0.05557015 -0.76081151  0.42648957]
 [ 0.5215701   0.1225544   0.54193436]
 [-0.01240881  0.04546566 -0.14491796]]
Вектор-стовпчик сум елементів кожного рядка:
[[-0.38989208]
 [ 1.18605885]
 [-0.11186111]]
